### ISSUE TITLE
 个别番号刮削错误。line 107, in <module>     status, genres_db = scrape_from_db(jav_file, jav_model, handler.url_db, handler.proxy_db

### ISSUE THREAD

**Issue by Swiftfrog** [JustMachiavelli/javsdt#127]
File "D:\JAVSDT-updated\javsdt-master\src\Youma.py", line 107, in <module>
    status, genres_db = scrape_from_db(jav_file, jav_model, handler.url_db, handler.proxy_db)
  File "D:\JAVSDT-updated\javsdt-master\src\Functions\Web\Javdb.py", line 73, in scrape_from_db
    print(f'    >获取信息: {url_jav}')
UnboundLocalError: local variable 'url_jav' referenced before assignment
\KEED-69.mp4
    >第2个失败！发生错误，如一直在该影片报错请截图并联系作者: Traceback (most recent call last):
  File "D:\JAVSDT-updated\javsdt-master\src\Youma.py", line 107, in <module>
    status, genres_db = scrape_from_db(jav_file, jav_model, handler.url_db, handler.proxy_db)
  File "D:\JAVSDT-updated\javsdt-master\src\Functions\Web\Javdb.py", line 73, in scrape_from_db
    print(f'    >获取信息: {url_jav}')
UnboundLocalError: local variable 'url_jav' referenced before assignment
\MBM-296.mp4
    >第3个失败！发生错误，如一直在该影片报错请截图并联系作者: Traceback (most recent call last):
  File "D:\JAVSDT-updated\javsdt-master\src\Youma.py", line 107, in <module>
    status, genres_db = scrape_from_db(jav_file, jav_model, handler.url_db, handler.proxy_db)
  File "D:\JAVSDT-updated\javsdt-master\src\Functions\Web\Javdb.py", line 73, in scrape_from_db
    print(f'    >获取信息: {url_jav}')
UnboundLocalError: local variable 'url_jav' referenced before assignment
\MHAR-01.mp4
    >第4个失败！发生错误，如一直在该影片报错请截图并联系作者: Traceback (most recent call last):
  File "D:\JAVSDT-updated\javsdt-master\src\Youma.py", line 107, in <module>
    status, genres_db = scrape_from_db(jav_file, jav_model, handler.url_db, handler.proxy_db)
  File "D:\JAVSDT-updated\javsdt-master\src\Functions\Web\Javdb.py", line 73, in scrape_from_db
    print(f'    >获取信息: {url_jav}')
UnboundLocalError: local variable 'url_jav' referenced before assignment
\MHAR-02.mp4
    >第5个失败！发生错误，如一直在该影片报错请截图并联系作者: Traceback (most recent call last):
  File "D:\JAVSDT-updated\javsdt-master\src\Youma.py", line 107, in <module>
    status, genres_db = scrape_from_db(jav_file, jav_model, handler.url_db, handler.proxy_db)
  File "D:\JAVSDT-updated\javsdt-master\src\Functions\Web\Javdb.py", line 73, in scrape_from_db
    print(f'    >获取信息: {url_jav}')
UnboundLocalError: local variable 'url_jav' referenced before assignment
\MHAR-07.mp4
    >第6个失败！发生错误，如一直在该影片报错请截图并联系作者: Traceback (most recent call last):
  File "D:\JAVSDT-updated\javsdt-master\src\Youma.py", line 107, in <module>
    status, genres_db = scrape_from_db(jav_file, jav_model, handler.url_db, handler.proxy_db)
  File "D:\JAVSDT-updated\javsdt-master\src\Functions\Web\Javdb.py", line 73, in scrape_from_db
    print(f'    >获取信息: {url_jav}')
UnboundLocalError: local variable 'url_jav' referenced before assignment
\MHAR-08.mp4

错误代码如上，跟javdb.py的有关，麻烦作者看一下，谢谢。

**Comment by lovelively** [comment]
同样的问题，不知道这次还有没有大佬帮忙修复

**Comment by bddiudiu** [comment]
车牌错误
